server:
  port: 9002

#配置Eureka Server
eureka:
  instance:
    hostname: eureka9002.com #服务实例名
  client:
    #配置不向注册中心注册
    register-with-eureka: false
    #表示自己就是注册中心，作用就是维护注册的服务实例，不需要去检索
    fetch-registry: false
    service-url:
      #这里注册到eureka9001 server
      defaultZone: http://eureka9001.com:9001/eureka/
#  server:
#    #是否开启自我保护机制，默认为true-开启，false-关闭
#    enable-self-preservation: false
#    #设置超时时间为2秒，即在2秒钟收不到心跳包，就认为是超时
#    eviction-interval-timer-in-ms: 2000